apiVersion: v1
kind: Service
metadata:
  name: devops-project-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30098
    protocol: TCP
    targetPort: 80
  selector:
    app: devops-project

